$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

In [ ]:
import numpy as np

A = np.array([[1,2,3], [2,3,4]]) 
A.shape


(3, 1)

$v_{m} =
 \begin{pmatrix}
  v_{1}\\
  v_{2} \\
  \vdots \\
  v_{m}
 \end{pmatrix}$

In [ ]:
v = np.array([1,2,3]).reshape(3,1) 
v.shape

In [ ]:
B=np.array([[10, 4, 9], [2,4,8],[20,4,18],[23, 7, 5]])
B.shape

(4, 3)

In [ ]:
A=np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
A+B

array([[10,  5, 11],
       [ 5,  8, 13],
       [26, 11, 26],
       [32, 17, 16]])

In [ ]:
A-B

array([[-10,  -3,  -7],
       [  1,   0,  -3],
       [-14,   3, -10],
       [-14,   3,   6]])

Use `np.random.rand` to create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
A=np.random.rand(4,3)*100
A

array([[81.19342664, 89.58654711,  2.27867658],
       [32.1106289 , 45.96559466, 80.13756286],
       [87.29760781, 15.52413651, 84.84097258],
       [34.42054192, 78.47835401, 85.88487181]])

Use `np.random.randn` to generates an array of given shape, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [ ]:
A=np.random.randn(12).reshape(4,3)
A

array([[ 0.69841657, -1.38368259,  1.08718092],
       [-3.38339883,  1.54657978, -1.99031818],
       [ 0.04623468,  1.04330996,  0.73284472],
       [ 0.92647437, -1.11638338,  0.25727282]])

In [ ]:
A+B

array([[10.69841657,  2.61631741, 10.08718092],
       [-1.38339883,  5.54657978,  6.00968182],
       [20.04623468,  5.04330996, 18.73284472],
       [23.92647437,  5.88361662,  5.25727282]])

The * operator can be used as a shorthand for np.multiply on ndarrays

In [ ]:
A*B

array([[  6.98416575,  -5.53473035,   9.78462829],
       [ -6.76679765,   6.18631911, -15.92254541],
       [  0.92469363,   4.17323986,  13.1912049 ],
       [ 21.30891049,  -7.81468368,   1.28636412]])